### ISSUE TITLE
auto-updater

### ISSUE THREAD

**Issue by RustoMCSpit** [open-audio-stack/open-audio-stack-core#11]
https://github.com/orgs/open-audio-stack/projects/2?pane=issue&itemId=85472022&issue=open-audio-stack%7Copen-audio-stack-core%7C6

if this is getting a different repo, move this issue

if something is out of date, it should auto-update.
this may rely on tracking downloads or user accounts unless you want users to locally download huge .yaml files and have open audio scan that and compare against its system which i think is a poor implementation

**Comment by kmturley** [comment]
There is an update method, which will sync the latest registry locally.
Package Manager will be able to control when to update the registry.
So in that sense it will be auto-updating already, we don't need this feature request!
